### ISSUE TITLE
Update covid_latest_SC_FULL.json

### ISSUE THREAD

**Issue by krumware** [jackneil/covidsc-web#25]
covid_latest_SC_FULL.json needs some trimmings and additions so we can optimize data downloads.

 - [x] Add the `{"Country":"USA","State":"ALL","County":"ALL",` entry from the full dataset
 - [x] Remove non-USA entries ie: `{"Country":"BRA","State":"SC","County":"ALL",`
 - [x] Turn on gzip compression in AWS https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

**Comment by jackneil** [comment]
to use the gzip just include 'Accept-Encoding: gzip' in the request header.
Also ... use this file to get just SC latest data (which is a much smaller filesize)
https://aws.covidsc.com/data/covid_latest_SC.json

**Comment by krumware** [comment]
We've always included that header, chrome does it by default. Just re-ran lighthouse and that audit looks good to go now.

@jackneil we need to use covid_latest_SC_FULL to get the multi-day counts for the graph.
I'm still using covid_latest_SC as a separate fetch since it's only 20kb
