### ISSUE TITLE
USA vs. SC data

### ISSUE THREAD

**Issue by kbakeann** [jackneil/covidsc-web#7]
What exactly are we trying to tell our users by showing the cases and deaths for SC and the USA?

Are we comparing SC cases to US cases and SC deaths to US deaths?
Are we comparing SC deaths to SC cases and, separately, US deaths to US cases?

IF it's the latter, is showing the data for the US necessary?

I'm just trying to get a better picture here so we can more intuitively show that data within the app.

**Comment by jackneil** [comment]
I don't think the US numbers are mandatory to show but I imagine most people would like to see those numbers. Maybe it is collapsable and starts out collapsed?

**Comment by kbakeann** [comment]
@jackneil Okay! What about the [+2] under the initial number? What exactly does that represent?

**Comment by jackneil** [comment]
Those '+' items are the daily change in cases/deaths, respectively

**Comment by kbakeann** [comment]
Okay, that's what I figured. Thank you! I'll leave this issue open for now so if I have any more questions I can just put them here for documentation.
